ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path, include
from cart import views
app_name ="cart"

urlpatterns = [
    path('cart/<n>',views.cart, name='cart'),
    path('cartview',views.cartview, name='cartview'),
    path('cart_remove/<n>',views.cart_remove, name='cart_remove'),
    path('full_remove/<n>',views.full_remove, name='full_remove'),
    path('orderform',views.orderform, name='orderform'),
    path('orderVIEW', views.orderview, name='orderview'),



]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('cart.urls')),
    path('search/',include('search.urls'))
]

# Serve media files in DEBUG mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path, include
from search import views
app_name="search"

urlpatterns = [
   path('search',views.search, name='search'),


]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('productdetail/<p>',views.productdetail,name='productdetail'),
    path('detail/<p>/',views.detail, name='detail'),
    path('register',views.register, name='register'),
    path('login',views.user_login, name='user_login'),
    path('logout',views.user_logout, name='logout'),

]

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product
from django.http import HttpResponse
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    ordered_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum= models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from shop.models import Product
from cart.models import Cart,Account,Order


@login_required
def cartview(request):
    total=0
    u = request.user
    try:
        cart = Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.product.price
    except:
        pass
    return render(request, 'cart.html', {'c': cart,'total':total})


@login_required
# Create your views here.
def cart(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (p.stock > 0):
            cart.quantity += 1
            cart.save()
            p.stock -= 1
            p.save()

    except:
        if (p.stock > 0):
            cart = Cart.objects.create(product=p, user=u, quantity=1)
            cart.save()
            p.stock-=1
            p.save()

    return redirect('cart:cartview')
@login_required
def cart_remove(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity >1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()

        else:
            cart.delete()
            p.stock += 1
            p.save()

    except:
       pass

    return redirect('cart:cartview')
@login_required
def full_remove(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
       pass

    return cartview(request)
@login_required
def orderform(request):
    if request.method=="POST":
        a=request.POST['a']
        ph = request.POST['ph']
        an = request.POST['an']

        u=request.user
        cart=Cart.objects.filter(user=u)
        total=0
        for i in cart:
            total+=i.quantity*i.product.price
        try:
            ac=Account.objects.get(acctnum=an)#to retrive the acctobject
            if ac.amount>= total:
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=ph,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="Your order placed successfully"
                return render(request,"orderdetail.html",{'msg':msg})

            else:
                msg="insufficient amount,you can't place order"
                return render(request, "orderdetail.html", {'msg': msg})
        except:
            pass

    return render(request,'orderform.html')

# def orderform(request):
#     if (request.method == 'POST'):
#         a = request.POST['a']
#         ph = request.POST['ph']
#         an = request.POST['an']
#         u=request.user
#         cart=Cart.objects.filter(user=u)
#
#         total=0
#         for i in cart:
#             total+=i.quantity*i.product.price
#
#         try:
#
#             ac=Account.objects.get(acctnum=an)
#             if(ac.amount >= total):
#                 ac,amount=ac.amount-total
#                 ac.save()
#                 for i in cart:
#                     o=Order.objects.create(user=u,product=i.product,address=a,phone=ph,no_of_items=i.quantity,order_status="paid")
#                     o.save()
#                 cart.delete()
#                 msg="your order placed succesfully"
#                 return render(request,'orderdetail.html',{'msg': msg})
#             else:
#                 msg = "Insufficient amount cant place your order "
#                 return render(request, 'orderdetail.html', {'msg': msg})
#         except:
#             pass
#
#
#
#
#
#     return render(request, 'orderform.html')



@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o})

ecommerce/search/views.py
from django.shortcuts import render
from django.db.models import Q
from shop.models import Product

# Create your views here.
def search(request):
    b = None
    q = ""
    if (request.method == "POST"):
        q = request.POST['q']
        if q:
            b = Product.objects.filter(Q(name__icontains=q) | Q(desc__icontains=q))
    return render(request, 'search.html', {'q': q, 'b': b})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Neuton:ital,wght@0,200;0,300;0,400;0,700;0,800;1,400&display=swap"
        rel="stylesheet">
    <!--    icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>
        <center>
            <img src="{% static 'images/shopit_logo.png'%}" height="100px" width="100px">
            <nav class="navbar navbar-expand-lg navbar-light ">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">SHOP-IT</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <!--                                <a class="nav-link" href="#">Products</a>-->
                            </li>
                            {% if user.is_authenticated %}

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    All-Categories
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    {% for i in links %}
                                    <li><a class="dropdown-item"
                                            href="{% url 'shop:productdetail' i.name %}">{{i.name}}</a></li>
                                    {% endfor %}

                                    <hr class="dropdown-divider">

                                    <!--                                    <li><a class="dropdown-item" href="#">Others</a></li>-->
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'shop:logout' %}" tabindex="-1" aria-disabled="true">logout</a>
                            </li>
                            {% if user.is_superuser == False %}
                             <li class="nav-item">
                                <a class="nav-link " href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup class="ms-2">{{count}}</sup></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'cart:orderview' %}">Your Orders</a>
                            </li>
                            {% endif %}



                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'shop:register' %}" tabindex="-1" aria-disabled="true">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'shop:user_login' %}" tabindex="-1" aria-disabled="true">login</a>

                            </li>
                            {% endif %}

                        </ul>
                        <form class="d-flex"   method="POST" action="{% url 'search:search' %}">
                        {% csrf_token %}
                            <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>

                    </div>
                </div>
            </nav>

        </center>
    </header>
    <div>
        {% block content %}
        {% endblock %}
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col">
                    <p>&copy; 2024 Shop-it Pvt ltd. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
    </div>
</body>

</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1> Cart!!</h1>
<center>
    <div class="container mt-5" style="margin-bottom :100px;">
        <div class="row ">
            <h1>Shopping Cart</h1>
            <h4>-Fill up fast!!!-</h4>
            <div class="col-7">
                <table class="table table-bordered">
                    <tr>
                        <th colspan="5">Cart-Items</th>
                    </tr>
                    {% for i in c %}
                        <tr>
                            <td>
                                <img src="{{ i.product.image.url }}" height="200px" width="200px">

                            </td>
                            <td>
                                <p>{{i.product.name}}</p>
                            </td>
                            <td>
                                <h6>Productid:{{i.product.id}}</h6>
                                <h6>Unit Price:{{i.product.price}}</h6>
                                <h6>Quantity: {{i.quantity}}*{{i.product.price}}</h6>



                            </td>
                            <td>Subtotal:{{i.subtotal}}</td>

                            <td>
                                {% if i.product.stock > 0 %}
                                <a href="{% url 'cart:cart' i.product.name %}"><i class="fa-solid fa-circle-plus"></i></a>
                                <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                                <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                                {% else %}
                                <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                                <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash"></i></a>
                                {% endif %}
                            </td>

                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-4">
                <table class="table table-bordered">
                    <tr>
                        <th colspan="5">Check Out</th>
                    </tr>
                    <tr><td>Total= {{total}}</td></tr></table><br>
                    <a href="{% url 'cart:orderform' %}" class="btn btn-success" style="position:absolute;right:480px;">place order</a>
                    <a href="{% url 'shop:allcat' %}" class="btn btn-success" style="position:absolute;right:300px;">Continue shopping</a>

            </div>
        </div>
    </div>
</center>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div>
    <img src="{% static 'images/bannerimg.png'%}" width="100%">
  </div>
  <div class="container-fluid mt-3" style="margin-bottom: 100px;">
    <h1 class="text-center fw-bold">'Behind the Brand'</h1>
    <p style="text-align: justify; line-height: 2;">
      Welcome to Shop It, your ultimate online destination for a seamless and delightful shopping experience! At Shop It, we bring you a curated selection of the latest trends, premium products, and must-have items, all conveniently at your fingertips. Discover a world of fashion, electronics, home decor, beauty essentials, and much more, all thoughtfully organized to make your shopping journey effortless. Our user-friendly interface ensures that you can easily navigate through a diverse range of categories, finding exactly what you need with just a few clicks. Embrace the joy of online shopping with Shop It's secure and hassle-free checkout process. We prioritize your privacy and security, providing a safe environment for you to explore, select, and purchase your favorite items. Our streamlined order tracking and quick delivery options ensure that your purchases reach you promptly and in pristine condition. Engage with our vibrant community through product reviews, ratings, and recommendations, making informed decisions and staying connected with the latest trends. Explore exclusive deals, discounts, and seasonal offers that make every purchase on Shop It a rewarding experience. Whether you're searching for the perfect outfit, upgrading your tech gadgets, or enhancing your living space, Shop It is here to cater to your every need. Elevate your online shopping experience with Shop It – where style, convenience, and affordability converge to create an unparalleled digital marketplace. Shop It, your one-stop destination for all things fabulous!
    </p>
  </div>
  <div class="container-fluid" style="margin-bottom: 180px;">
    <div class="row justify-content-center">
      {% for i in c %}
        <div class="col-sm-4 mb-4">
          <div class="card mx-auto">
            <img src="{{ i.images.url }}" height="200px" width="50%" class="card-img-top" alt="">
            <div class="card-body">
              <h5 class="card-title text-center">{{ i.name }}</h5>
              <a href="{% url 'shop:productdetail' i.name %}" class="btn btn-success d-block mx-auto">Products</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

ecommerce/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5" style="margin-bottom :100px;">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ p.image.url }}" style="height: 400px; width: 400px;" alt="{{ p.name }}">
        </div>
        <div class="col-md-6">
            <div class="choco">
                <h3>{{ p.name }}</h3>
                <p>{{ p.desc }}</p>
                <h5>stock<br>{{ p.stock }}</h5>
                <h3>Price  <br>₹ {{p.price}}</h3>
            </div>
            <div>
                {% if user.is_superuser == True %}
                    {% if p.stock == 0 %}
                    <h2>out of stock</h2>
                    <a href="{% url 'admin:index' %}" class="btn btn-success d-block mx-auto">Add Stock</a>
                    {% else %}
                    <h2>In stock</h2>
                    <a href="{% url 'admin:index' %}" class="btn btn-success d-block mx-auto">Add Stock</a>
                    {% endif %}
                {% else %}
                    {% if p.stock == 0 %}
                    <h2>out of stock</h2>
                    {% else %}
                    <a href="{% url 'cart:cart' p.name %}" class="btn btn-success d-block mx-auto">Add to cart</a>
                    {% endif %}
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>LOGIN USER</h3>

<center>
<form method="POST" >
  {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control"  name="u" placeholder="Enter the username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter the password">
</div>
    <div class="mb-3">
  <input type="submit" class="form-control btn btn-danger">
    </div>
</form>
    </center>
{% endblock %}

ecommerce/templates/orderdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <center>
        <h4 class="text-center text-success">{{msg}}</h4>
        <h4 class="text-center text-success">Thank you!!!</h4>
        <h4 class="text-center "><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h4>


    </center>
</div>

{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <h3>Order please!!!</h3>

  <form method="POST" style="padding:20px;">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Address</label>
      <input type="text" class="form-control"  name="a" placeholder="Enter the address">
    </div>
    <div class="mb-3">
      <label class="form-label">Phone </label>
      <input type="number" class="form-control" name="ph" placeholder="Enter the phone number">
    </div
    <div class="mb-3">
      <label class="form-label">Account Number</label>
      <input type="number" class="form-control" name="an" placeholder="Enter the account number">
    </div>
      <div>
      <input type="submit" class="form-control btn btn-danger" >
    </div>
  </form>

</center>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Name of the Customer</th>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Delivery Address</th>
                <th>No. of Items</th>
                <th>Ordered On</th>
                <th>Delivery Status</th>
                <th>Product Image</th>
            </tr>
        </thead>
        <tbody>
            {% for i in o %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ i.product.name }}</td>
                    <td>{{ i.product.price }}</td>
                    <td>{{ i.address }}</td>
                    <td>{{ i.no_of_items }}</td>
                    <td>{{ i.ordered_date }}</td>
                    <td style="color: #B7CAB4;">{{ i.delivery_status }}</td>
                    <td><img src="{{ i.product.image.url }}" height="100px" width="100px"></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
pwd

ecommerce/templates/productdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<img src="{{ c.images.url }}" style="height: 400px; width: 100%">
<h3>{{ c.name }}</h3>
<p>{{ c.desc }}</p>
<div class="container-fluid" style="margin-bottom: 180px;">
  <div class="row justify-content-center">
    {% for i in p %}
      <div class="col-sm-4 mb-5">
        <div class="card">
          <img src="{{ i.image.url }}" height="200px" width="100%" class="card-img-top" alt="">
          <div class="card-body">
            <h5 class="card-title text-center">{{ i.name }}</h5>
            <p class="card-text text-center">{{ i.price }}</p>
            <a href="{% url 'shop:detail' i.name %}" class="btn btn-success d-block mx-auto">Details</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}
</body>
</html>

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>REGISTER USER</h3>
<center>

  <form method="POST" >
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Username</label>
      <input type="text" class="form-control"  name="u" placeholder="Enter the username">
    </div>
    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p" placeholder="Enter the password">
    </div>
    <div class="mb-3">
      <label class="form-label">Confirm Password</label>
      <input type="password" class="form-control" name="c" placeholder="Confirm password">
    </div>
    <div class="mb-3">
      <label class="form-label">Email address</label>
      <input type="email" class="form-control" name="e" placeholder="name@example.com">
    </div>
    <div class="mb-3">
      <label class="form-label">First name</label>
      <input type="text" class="form-control"  name="f" placeholder="Enter the first name">
    </div>
    <div class="mb-3">
      <label class="form-label">Last Name</label>
      <input type="text" class="form-control" name="l" placeholder="Enter the last name">
    </div>
<!--    <div class="mb-3">-->
<!--      <label class="form-label">Phone number</label>-->
<!--      <input type="number" class="form-control" name="n" placeholder="Enter the phone number">-->
<!--    </div>-->
<!--    <div class="mb-3">-->
<!--      <label class="form-label">Place</label>-->
<!--      <input type="text" class="form-control" name="pl" placeholder="Enter the Place">-->
<!--    </div>-->
    <div class="mb-3">
      <input type="submit" class="form-control btn btn-danger">
    </div>
  </form>

</center>
{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <center>
        <div class="container mt-5" style="margin-bottom: 100px;">
            <h1 class="text-center">Search</h1>
            <h4 class="text-center">You have searched for query {{ q }}</h4>

            {% if b %}
                <div class="row mt-4 justify-content-center">
                    {% for i in b %}
                        <div class="col-md-4 mb-4">
                            <div class="card">
                                <img src="{{ i.image.url }}" class="card-img-top" alt="{{ i.name }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ i.name }}</h5>
                                    <p class="card-text">{{ i.desc }}</p>
                                    <p class="card-text">Price: {{ i.price }}</p>
                                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-success d-block mx-auto">Details</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="text-center">
                    <b><p>No results found</p></b>
                </div>
            {% endif %}
        </div>
    </center>
{% endblock %}